version: '3'

services:
  backend:
    build: ./
    depends_on:
      - database
    environment:
      - PORT=4200
      - db=database
    ports:
      - 2000:4200
    links:
      - database:database
  database:
    build: ./database
    volumes:
      - ./database/data:/var/lib/mysql